# Generated by Django 5.0 on 2024-02-15 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='blog',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='blog',
            new_name='post',
        ),
    ]
